//*****************************************************************************
// Filename : 'expr.c'
// Title    : Expression evaluator for MONOCHRON Emulator
//*****************************************************************************
#include <stdio.h>
#include "expr.h"
#include "listvarutil.h"

// The expression evaluator is generated by bison/flex using expr.y and expr.l.
// The generated c source code is then inserted below using #include's and
// built using standard makefile dependency rules.
#include "expr.tab.c"
#include "expr.yy.c"

